name: ILP Drone Service CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out code from the repository
      - uses: actions/checkout@v4

      # 2. Set up the Java environment (JDK 17)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # 3. (Optional) Run the ILP Service Mock
      - name: Build and Test with Maven
        run: mvn -B package --file pom.xml
        env:
          # Dummy value to prevent context loading errors if your Service checks this on startup
          ILP_ENDPOINT: "https://ilp-rest.azurewebsites.net/"